### ISSUE TITLE
[TODO] By next week

### ISSUE THREAD

**Issue by rkutty1** [agrija9/Software-Development-Project#18]
![GUI_prototype](https://user-images.githubusercontent.com/34669548/68400050-accbe100-0177-11ea-911d-26ca8ac7a136.jpg)
- [x] Work GUI (attached image below)
- [x] Write test cases
- [x] Integrate Travis build to Readme

- [x] Filter Topics based on string type only

**Comment by deebuls** [comment]
Convert the above diagram into a digital diagram and move it folder documentation along with the explanation of what each block in the diagram .
