### ISSUE TITLE
[TODO]

### ISSUE THREAD

**Issue by rkutty1** [agrija9/Software-Development-Project#25]
- [x] Add dashed lines between topics with e_start and e_end
- [x] Write README with installation steps to run on personal computer
- [x] Add rosbag dependency in requirement.txt
* This week 
- [x] Clean repository
- [x] Installation steps to be stated on github
- [x] Put travis build badge
- [x] Make repo public
